site_name: PicoKeys Documentation
site_description: Documentation for Pico HSM, Pico FIDO, Pico OpenPGP and PicoKeyApp
site_url: https://docs.picokeys.com/
site_dir: site

theme:
  name: material
  language: en
  logo: assets/images/picokeys.png
  favicon: assets/images/favicon.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
  - assets/stylesheets/extra.css

nav:
  - Home: index.md

  - PicoKeyApp:
      - Overview: picokeyapp/index.md
      - Concepts: picokeyapp/concepts.md
      - Installation: picokeyapp/install.md
      - First steps: picokeyapp/first-steps.md
      - Quick start: picokeyapp/quickstart.md
      - Troubleshooting: picokeyapp/troubleshooting.md
      - Usage guide:
        - Home screen: picokeyapp/home.md
        - Device configuration: picokeyapp/configuration.md
        - Firmware management: picokeyapp/firmware.md
        - About: picokeyapp/about.md
        - License: picokeyapp/license.md

  - Pico HSM:
      - Overview: picohsm/index.md
      - Supported features: picohsm/features.md
      - Usage:
        - First steps: picohsm/first-steps.md
        - Key Generation: picohsm/key-generation.md
        - AES: picohsm/aes.md
        - Asymmetric Ciphering: picohsm/asymmetric-ciphering.md
        - Sign & Verify: picohsm/sign-verify.md
        - Public Key Authentication: picohsm/public-key-authentication.md
        - Backup & Restore: picohsm/backup-restore.md
        - Store Data: picohsm/store-data.md
        - Smart Card Shell 3: picohsm/scs3.md

  - Pico FIDO:
      - Overview: picofido/index.md

  - Pico OpenPGP:
      - Overview: pico-openpgp/index.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
